name: Build

on:
  push:
  pull_request:
  release:
    types: 
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.mod

      - name: Build executable
        run: |
          go build -o build/reggen github.com/liteldev/reggen

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: reggen
          path: build/reggen

  upload-release:
    name: Upload release
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: reggen
          path: build

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: build/reggen